extensions:
# Detected files with this extension are downloaded to the Captures 
# directory by default. Any changes must use the same format.
# This section cannot be empty.
    - '7z'
    - 'bat'
    # - 'bz2'
    - 'crypt'
    - 'dll'
    - 'doc'
    - 'docx'
    - 'exe'
    # - 'gz'
    - 'hta'
    # - 'iso'
    - 'jar'
    - 'lnk'
    - 'm68k'
    - 'mips'
    - 'mpsl'
    # - 'php'
    - 'ppc'
    - 'ppt'
    - 'ps1'
    - 'py'
    # - 'rar'
    - 'rumba'
    - 'sh'
    - 'sh4'
    - 'spc'
    # - 'tar'
    - 'vb'
    - 'vbs'
    - 'xls'
    - 'xlsx'
    # - 'xml'
    - 'zip'

# ------------------------------------------------------------------------------

keywords:
# Any changes must use the same format.
# This section cannot be empty.

# Generic
    'account': 35
    'activity': 40
    'alert': 25
    'authenticate': 60
    'authentication': 70
    'authorize': 45
    'bill': 20
    'client': 30
    'confirm': 35
    'credential': 50
    'customer': 40
    'form': 20
    'invoice': 35
    'live': 20
    'loan': 20
    'log-in': 30
    'login': 25
    'lottery': 35
    'manage': 30
    'office': 30
    'online': 30
    'password': 40
    'portal': 30
    'purchase': 40
    'recover': 35
    'refund': 30
    'rezulta': 35
    'safe': 20
    'secure': 30
    'security': 40
    'service': 35
    'sign-in': 35
    'signin': 30
    'support': 35
    'tax': 15
    'transaction': 55
    'unlock': 30
    'update': 30
    'verification': 60
    'verify': 30
    'wallet': 30
    'webscr': 30

# Apple iCloud
    'apple': 25
    'appleid': 35
    'icloud': 30
    'iforgot': 35
    'itunes': 30

# Bank/money
    'advcash': 35
    'atb': 15
    'ameritrade': 50
    'bank': 20
    'bankofamerica': 65
    'barclays': 40
    'bmo': 15
    'bibox': 25
    'bmo': 15
    'cibc': 20
    'citigroup': 45
    'desjardins': 50
    'discovercard': 60
    'gofund': 30
    'hsbc': 20
    'ing': 15
    'meridian': 40
    'merilledge': 50
    'moneygram': 45
    'morganstanley': 65
    'okpay': 25
    'payeer': 30
    'paypal': 30
    'payza': 25
    'perfectmoney': 60
    'royalbank': 45
    'santander': 45
    'scotia': 30
    'scottrade': 45
    'skrill': 30
    'solidtrustpay': 65
    'wellsfargo': 50
    'westernunion': 60

# Cryptocurrency
    'bitconnect': 50
    'bitfinex': 40
    'bitflyer': 40
    'bithumb': 35
    'bitmex': 30
    'bitstamp': 40
    'bittrex': 35
    'blockchain': 50
    'coinbase': 40
    'coinhive': 40
    'coinsbank': 45
    'entromoney': 50
    'hitbtc': 30
    'kraken': 30 # some false positives
    'lakebtc': 35
    'localbitcoin': 60
    'poloniex': 40
    'webmoney': 40

# Ecommerce
    'amazon': 30
    'overstock': 45
    'alibaba': 35
    'aliexpress': 50
    'leboncoin': 45

# Email
    'gmail': 25
    'google': 30
    'hotmail': 35
    'microsoft': 45
    'office365': 45
    'onedrive': 40
    'outlook': 35
    'protonmail': 50
    'tutanota': 40
    'windows': 35
    'yahoo': 25
    'yandex': 30

# Malware
    '16shop': 30
    'agenttesla': 50
    'arkei': 25
    'azorult': 35
    'batman': 30
    'betabot': 35
    'botnet': 30
    'diamondfox': 50
    'emotet': 30
    'formbook': 40
    'gaudox': 30
    'gorynch': 35
    'iceIX': 25
    'kardon': 30
    'keybase': 35
    'kronos': 30
    'litehttp': 40
    'lokibot': 35
    'megalodon': 45
    'mirai': 25
    'neutrino': 40
    'pekanbaru': 45
    'predatorthethief': 80
    'quasar': 30
    'rarog': 25
    'tesla': 25
    'ursnif': 30
    'workhard': 40

# Security
    '1password': 45
    'dashlane': 40
    'lastpass': 40
    'nordvpn': 35
    'protonvpn': 45
    'tunnelbear': 50

# Social Media
    'facebook': 40
    'flickr': 30
    'instagram': 45
    'linkedin': 40
    'reddit': 30
    'tumblr': 30
    'twitter': 35
    'whatsapp': 40
    'youtube': 35 # some false positives

# Other
    'adobe': 25
    'cabletv': 35
    'coxcable': 40
    'directtv': 40
    'docusign': 40
    'dropbox': 35
    'ebay': 20
    'github': 30
    'mydish': 30
    'netflix': 35
    'skype': 25
    'spotify': 35
    'trello': 30
    'verizon': 35

# Miscellaneous & SE tricks
    '-com.': 15
    '-gouv-': 20
    '.com-': 15
    '.com.': 15
    '.gouv-': 20
    '.gouv.': 20
    '.gov-': 15
    '.gov.': 15
    '.net-': 15
    '.net.': 15
    '.org-': 15
    '.org.': 15
    'cgi-bin': 30

# FR specific
    'laposte': 35
    'suivi': 25

# BE specific
    'argenta': 35
    'belfius': 35
    'beobank': 35
    'bepost': 30
    'crelan': 30
    'europabank': 50
    'fintro': 30
    'fortis': 30
    'keytrade': 40
    'mobileviking': 60
    'nagelmackers': 60
    'proximus': 40
    'rabobank': 40

# Testing
    'absabank': 40
    'accurint': 40
    'aetna': 25
    'allegro': 35
    'alliancebank': 60
    'amarillo': 40
    'americanairlines': 80
    'americanexpress': 75
    'americangreetings': 85
    'arenanet': 40
    'associatedbank': 70
    'bancadiroma': 55
    'bancaintesa': 55
    'bancasa': 35
    'bancodebrasil': 65
    'bancoreal': 45
    'bankmillennium': 70
    'bankofkc': 40
    'bankofthewest': 65
    'bendigo': 35
    'binance': 35
    'blizzard': 40
    'bloomspot': 45
    'bradesco': 40
    'buywithme': 45
    'cahoot': 30
    'caixa': 25
    'caixo': 25
    'capitalone': 50
    'capitecbank': 55
    'careerbuilder': 65
    'cariparmacreditagricole': 115
    'cartasi': 35
    'centurylink': 55
    'charterone': 50
    'cielo': 25
    'cimbbank': 40
    'citibank': 40
    'citizens': 40
    'comerica': 40
    'commonwealthbankofaustralia': 135
    'compass': 35
    'cooperativebank': 75
    'craigslist': 50
    'creditkarma': 55
    'crown': 25
    'creditunionaustralia': 100
    'delta': 25
    'deutschebank': 60
    'dinersclub': 50
    'discoverbank': 60
    'discovery': 45
    'downeysavings': 65
    'egold': 25
    'eppicard': 40
    'fifththirdbank': 70
    'firstdirect': 55
    'firstfederalbankofcalifornia': 40
    'firstnationalbank': 85
    'franklin': 40
    'groupon': 35
    'gruppocarige': 60
    'gtbank': 30
    'guildwars2': 50
    'habbo': 25
    'halifax': 35
    'hmrc': 20
    'homerun': 35
    'huntington': 50
    'idex': 20
    'independentbank': 75
    'interactivebrokers': 90
    'intesasanpaolo': 70
    'itau': 20
    'kauaicreditunion': 80
    'keybank': 35
    'kiwibank': 40
    'lasalle': 35
    'littlewoods': 55
    'livingsocial': 60
    'lloydsbank': 50
    'localbitcoins': 65
    'lottomatica': 55
    'mastercard': 50
    'mbtrading': 45
    'metrobank': 45
    'mycrypto': 40
    'myetherwallet': 65
    'mymonero': 40
    'myspace': 35
    'nantucketbank': 65
    'nationalcity': 60
    'nationwide': 50
    'natwest': 35
    'nedbank': 35
    'netsuite': 40
    'nexon': 25
    'nordea': 30
    'northernrock': 60
    'orkut': 25
    'otomoto': 35
    'pagseguro': 45
    'paxful': 30
    'paypal': 30
    'peoples': 35
    'permanenttsb': 60
    'pintrest': 40
    'playdom': 35
    'playfish': 40
    'plumdistrict': 60
    'pncbank': 35
    'poste': 25
    'rackspace': 45
    'runescape': 45
    'safranational': 65
    'bankofnewyork': 65
    'salemfive': 45
    'salesforce': 50
    'santanderuk': 55
    'scotiabank': 50
    'skyfinancial': 60
    'smilebank': 45
    'southafricanrevenueservice': 130
    'standardbank': 60
    'steam': 25
    'stgeorgebank': 60
    'suncorp': 35
    'swedbank': 40
    'tamfidelidade': 65
    'tdcanadatrust': 65
    'tesco': 25
    'tibia': 25
    'tippr': 25
    'unicredit': 45
    'usaa': 20
    'usairways': 45
    'usbank': 30
    'visa': 20
    'vodafone': 40
    'volksbankenraiffeisenbanken': 135
    'wachovia': 40
    'walmart': 35
    'washingtonmutual': 80
    'westpac': 35
    'worldofwarcraft': 75
    'xapo': 20
    'zynga': 25

# ------------------------------------------------------------------------------

queries:
# Any changes must use the same format.
# This section cannot be empty.
    'automatic': 'task.method%3Aautomatic'
    'manual': 'task.method%3Amanual'
    'certstream': '(task.source%3Acertstream-idn OR task.source%3Acertstream-suspicious)'
    'openphish': 'task.source%3Aopenphish'
    'phishtank': 'task.source%3Aphishtank'
    'twitter': '(task.source%3Atwitter OR task.source%3Atwitter_illegalFawn OR task.source%3Atwitter_phishingalert)'
    'urlhaus': 'task.source%3Aurlhaus'

# ------------------------------------------------------------------------------

tlds:
# Any changes must use the same format.
# This section cannot be empty.
    - '.bank'
    - '.business'
    - '.cc'
    - '.center'
    - '.cf'
    - '.click'
    - '.club'
    - '.country'
    - '.download'
    - '.ga'
    - '.gb'
    - '.gdn'
    - '.gq'
    - '.info'
    - '.kim'
    - '.loan'
    - '.men'
    - '.ml'
    - '.mom'
    - '.online'
    - '.party'
    - '.pw'
    - '.racing'
    - '.ren'
    - '.review'
    - '.science'
    - '.stream'
    - '.study'
    - '.support'
    - '.tech'
    - '.tk'
    - '.top'
    - '.vip'
    - '.win'
    - '.work'
    - '.xin'
    - '.xyz'

# ------------------------------------------------------------------------------

exclusions:
# Any changes must use the same format.
    - '\.amazonaws\.com$'
    - '\.appdomain\.cloud$'
    - '\.azure\.com$'
    - '\.brilliantpocket\.com$'
    - '\.certsbridge\.com$'
    - '\.cibc\.com$'
    - '\.cloudflaressl\.com$'
    - '\.cloudshell\.dev$'
    - '\.com\.br\.orzzi\.com$'
    - '\.composedb\.com$'
    - '\.composedb\.direct$'
    - '\.edu$'
    - '\.filemaker-cloud\.com$'
    - '\.google\.com$'
    - '\.gov$'
    - '\.honeywell\.com$'
    - '\.intuit\.com$'
    - '\.legalbrandmarketing\.com$'
    - '\.microsoft\.com$'
    - '\.mil$'
    - '\.mybluemix\.net$'
    - '\.netflix\.com$'
    - '\.playapps\.download$'
    - '\.remotewd\.com$'
    - '\.usgovcloudapi\.net$'
    - '\.vmwarevmc\.com$'
    - '\.windows\.net$'
    - '\.zendesk-staging\.com$'
    - '^(\w+-)+[a-f0-9]{8}'
    - '^autodiscover\.'
    - '^gameflex\.'
    - '^iframes\.ampify\.ga$'
    - '^STH-for-'
    - '^www\.'
    - 'chat\.kowari\.macmoney\.co\.za$'
    - 'facebook\.sitechs\.net$'

# Testing
    - '\.absabank\..{2,3}$'
    - '\.accurint\..{2,3}$'
    - '\.aetna\..{2,3}$'
    - '\.allegro\..{2,3}$'
    - '\.alliancebank\..{2,3}$'
    - '\.amarillo\..{2,3}$'
    - '\.americanairlines\..{2,3}$'
    - '\.americanexpress\..{2,3}$'
    - '\.americangreetings\..{2,3}$'
    - '\.arenanet\..{2,3}$'
    - '\.associatedbank\..{2,3}$'
    - '\.bancadiroma\..{2,3}$'
    - '\.bancaintesa\..{2,3}$'
    - '\.bancasa\..{2,3}$'
    - '\.bancodebrasil\..{2,3}$'
    - '\.bancoreal\..{2,3}$'
    - '\.bankmillennium\..{2,3}$'
    - '\.bankofkc\..{2,3}$'
    - '\.bankofnewyork\..{2,3}$'
    - '\.bankofthewest\..{2,3}$'
    - '\.bendigo\..{2,3}$'
    - '\.binance\..{2,3}$'
    - '\.blizzard\..{2,3}$'
    - '\.bloomspot\..{2,3}$'
    - '\.bradesco\..{2,3}$'
    - '\.buywithme\..{2,3}$'
    - '\.cahoot\..{2,3}$'
    - '\.caixa\..{2,3}$'
    - '\.caixo\..{2,3}$'
    - '\.capitalone\..{2,3}$'
    - '\.capitecbank\..{2,3}$'
    - '\.careerbuilder\..{2,3}$'
    - '\.cariparmacreditagricole\..{2,3}$'
    - '\.cartasi\..{2,3}$'
    - '\.centurylink\..{2,3}$'
    - '\.charterone\..{2,3}$'
    - '\.cielo\..{2,3}$'
    - '\.cimbbank\..{2,3}$'
    - '\.citibank\..{2,3}$'
    - '\.citizens\..{2,3}$'
    - '\.comerica\..{2,3}$'
    - '\.commonwealthbankofaustralia\..{2,3}$'
    - '\.compass\..{2,3}$'
    - '\.cooperativebank\..{2,3}$'
    - '\.craigslist\..{2,3}$'
    - '\.creditkarma\..{2,3}$'
    - '\.creditunionaustralia\..{2,3}$'
    - '\.crown\..{2,3}$'
    - '\.delta\..{2,3}$'
    - '\.deutschebank\..{2,3}$'
    - '\.dinersclub\..{2,3}$'
    - '\.discoverbank\..{2,3}$'
    - '\.discovery\..{2,3}$'
    - '\.downeysavings\..{2,3}$'
    - '\.egold\..{2,3}$'
    - '\.eppicard\..{2,3}$'
    - '\.fifththirdbank\..{2,3}$'
    - '\.firstdirect\..{2,3}$'
    - '\.firstfederalbankofcalifornia\..{2,3}$'
    - '\.firstnationalbank\..{2,3}$'
    - '\.franklin\..{2,3}$'
    - '\.groupon\..{2,3}$'
    - '\.gruppocarige\..{2,3}$'
    - '\.gtbank\..{2,3}$'
    - '\.guildwars2\..{2,3}$'
    - '\.habbo\..{2,3}$'
    - '\.halifax\..{2,3}$'
    - '\.hmrc\..{2,3}$'
    - '\.homerun\..{2,3}$'
    - '\.huntington\..{2,3}$'
    - '\.idex\..{2,3}$'
    - '\.independentbank\..{2,3}$'
    - '\.interactivebrokers\..{2,3}$'
    - '\.intesasanpaolo\..{2,3}$'
    - '\.itau\..{2,3}$'
    - '\.kauaicreditunion\..{2,3}$'
    - '\.keybank\..{2,3}$'
    - '\.kiwibank\..{2,3}$'
    - '\.lasalle\..{2,3}$'
    - '\.littlewoods\..{2,3}$'
    - '\.livingsocial\..{2,3}$'
    - '\.lloydsbank\..{2,3}$'
    - '\.localbitcoins\..{2,3}$'
    - '\.lottomatica\..{2,3}$'
    - '\.mastercard\..{2,3}$'
    - '\.mbtrading\..{2,3}$'
    - '\.metrobank\..{2,3}$'
    - '\.mycrypto\..{2,3}$'
    - '\.myetherwallet\..{2,3}$'
    - '\.mymonero\..{2,3}$'
    - '\.myspace\..{2,3}$'
    - '\.nantucketbank\..{2,3}$'
    - '\.nationalcity\..{2,3}$'
    - '\.nationwide\..{2,3}$'
    - '\.natwest\..{2,3}$'
    - '\.nedbank\..{2,3}$'
    - '\.netsuite\..{2,3}$'
    - '\.nexon\..{2,3}$'
    - '\.nordea\..{2,3}$'
    - '\.northernrock\..{2,3}$'
    - '\.orkut\..{2,3}$'
    - '\.otomoto\..{2,3}$'
    - '\.pagseguro\..{2,3}$'
    - '\.paxful\..{2,3}$'
    - '\.paypal\..{2,3}$'
    - '\.peoples\..{2,3}$'
    - '\.permanenttsb\..{2,3}$'
    - '\.pintrest\..{2,3}$'
    - '\.playdom\..{2,3}$'
    - '\.playfish\..{2,3}$'
    - '\.plumdistrict\..{2,3}$'
    - '\.pncbank\..{2,3}$'
    - '\.poste\..{2,3}$'
    - '\.rackspace\..{2,3}$'
    - '\.runescape\..{2,3}$'
    - '\.safranational\..{2,3}$'
    - '\.salemfive\..{2,3}$'
    - '\.salesforce\..{2,3}$'
    - '\.santanderuk\..{2,3}$'
    - '\.scotiabank\..{2,3}$'
    - '\.skyfinancial\..{2,3}$'
    - '\.smilebank\..{2,3}$'
    - '\.southafricanrevenueservice\..{2,3}$'
    - '\.standardbank\..{2,3}$'
    - '\.steam\..{2,3}$'
    - '\.stgeorgebank\..{2,3}$'
    - '\.suncorp\..{2,3}$'
    - '\.swedbank\..{2,3}$'
    - '\.tamfidelidade\..{2,3}$'
    - '\.tdcanadatrust\..{2,3}$'
    - '\.tesco\..{2,3}$'
    - '\.tibia\..{2,3}$'
    - '\.tippr\..{2,3}$'
    - '\.unicredit\..{2,3}$'
    - '\.usaa\..{2,3}$'
    - '\.usairways\..{2,3}$'
    - '\.usbank\..{2,3}$'
    - '\.visa\..{2,3}$'
    - '\.vodafone\..{2,3}$'
    - '\.volksbankenraiffeisenbanken\..{2,3}$'
    - '\.wachovia\..{2,3}$'
    - '\.walmart\..{2,3}$'
    - '\.washingtonmutual\..{2,3}$'
    - '\.westpac\..{2,3}$'
    - '\.worldofwarcraft\..{2,3}$'
    - '\.xapo\..{2,3}$'
    - '\.zynga\..{2,3}$'
